name       : haskell-data-accessor
version    : 0.2.3
release    : 1
source     :
    - https://hackage.haskell.org/package/data-accessor-0.2.3/data-accessor-0.2.3.tar.gz : 1d583fd28b16093b408a741a1e05402280bb8f0e203c314dcf0f1391ffde3e38
license    : BSD-3-Clause
component  : programming.haskell
summary    : Utilities for accessing and manipulating fields of records
description: |
    Utilities for accessing and manipulating fields of records
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
